server:
  #端口号
  port: 8000
service:
  baseurl: manageSrv
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:*/mapper/*.xml
